api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
        html: ['text/html']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
