symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository

when@dev:
    symfonycasts_reset_password:
        # No throttle for testing
        throttle_limit: 1